[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

# This is not needed for Next.js and can actually cause issues
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
